<?php

/**
 * JavaScript Configuration Server
 * Serves the base URL configuration to JavaScript files
 */

// Include the base URL configuration
require_once __DIR__ . '/base_url.php';

// Set content type to JavaScript
header('Content-Type: application/javascript');

// Output the JavaScript configuration
echo "/**
* Base URL Configuration for JavaScript
* This file is dynamically generated by PHP to provide the correct base URL
* to all JavaScript files, making the application portable
*/

// Base URL constants for JavaScript
const BASE_URL = '" . BASE_URL . "';
const API_BASE_URL = '" . API_BASE_URL . "';
const ASSETS_BASE_URL = '" . ASSETS_BASE_URL . "';

// Helper function to build API URLs
function buildApiUrl(endpoint) {
    return API_BASE_URL + endpoint;
}

// Helper function to build asset URLs
function buildAssetUrl(path) {
    return ASSETS_BASE_URL + path;
}

// Helper function to build page URLs
function buildPageUrl(page) {
    return BASE_URL + page;
}

// Export for use in other modules (if using modules)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        BASE_URL,
        API_BASE_URL,
        ASSETS_BASE_URL,
        buildApiUrl,
        buildAssetUrl,
        buildPageUrl
    };
}
";
